/**
 * 
 */
package org.asd.kyros.shared.delta;

import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class FinishTypeFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public FinishTypeFormData() {
  }

  public GeneralDescription getGeneralDescription() {
    return getFieldByClass(GeneralDescription.class);
  }

  public ProcessName getProcessName() {
    return getFieldByClass(ProcessName.class);
  }

  public static class GeneralDescription extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public GeneralDescription() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class ProcessName extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public ProcessName() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }
}
