/**
 * 
 */
package org.asd.kyros.shared.alpha;

import java.util.Map;

import javax.annotation.Generated;

import org.asd.kyros.shared.delta.CompanyLookupCall;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.ValidationRule;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 * 
 * @generated
 */
@Generated(value = "org.eclipse.scout.sdk.workspace.dto.formdata.FormDataDtoUpdateOperation", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class PartFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public PartFormData() {
  }

  public Company getCompany() {
    return getFieldByClass(Company.class);
  }

  public ForQuoteOnly getForQuoteOnly() {
    return getFieldByClass(ForQuoteOnly.class);
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  public PartNumber getPartNumber() {
    return getFieldByClass(PartNumber.class);
  }

  public SearchWord getSearchWord() {
    return getFieldByClass(SearchWord.class);
  }

  public static class Company extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;

    public Company() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.LOOKUP_CALL, CompanyLookupCall.class);
      ruleMap.put(ValidationRule.ZERO_NULL_EQUALITY, true);
    }
  }

  public static class ForQuoteOnly extends AbstractValueFieldData<Boolean> {

    private static final long serialVersionUID = 1L;

    public ForQuoteOnly() {
    }
  }

  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public Name() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class PartNumber extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public PartNumber() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }

  public static class SearchWord extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;

    public SearchWord() {
    }

    /**
     * list of derived validation rules.
     */
    @Override
    protected void initValidationRules(Map<String, Object> ruleMap) {
      super.initValidationRules(ruleMap);
      ruleMap.put(ValidationRule.MAX_LENGTH, 4000);
    }
  }
}
